name: Backend Workflow

on:
  push:
    branches:
      - main
    paths:
      - backend

jobs:
  run:
  runs-on: ubuntu-latest

  steps:
    - name: "Say Hello World"
      run: |
        echo "Say, Hello World from Backend"
